version: '3'
services:
  mongodb:
    build:
      context: mongo
    image: ${REPO}/rs-mongodb:${TAG}
    networks:
      - robot-shop
  redis:
    image: redis:4.0.6
    networks:
      - robot-shop
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    networks:
      - robot-shop
  catalogue:
    build:
      context: catalogue
    image: signoz/rs-catalogue:latest
    environment: 
      - DD_AGENT_HOST=datadog-agent 
      - DD_SERVICE="catalogue"
    depends_on:
      - mongodb
    networks:
      - robot-shop
  user:
    build:
      context: user
    image: signoz/rs-user:latest
    environment: 
      - DD_AGENT_HOST=datadog-agent 
      - DD_SERVICE="user"
    depends_on:
      - mongodb
      - redis
    networks:
      - robot-shop
  cart:
    build:
      context: cart
    image: signoz/rs-cart:latest
    environment: 
      - DD_AGENT_HOST=datadog-agent 
      - DD_SERVICE="cart"
    depends_on:
      - redis
    networks:
      - robot-shop
  mysql:
    build:
      context: mysql
    image: ${REPO}/rs-mysql-db:${TAG}
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop
  shipping:
    build:
      context: shipping
    image: signoz/rs-shipping:latest
    environment: 
      - DD_AGENT_HOST=datadog-agent 
      - DD_SERVICE="shipping"
    depends_on:
      - mysql
    networks:
      - robot-shop
  ratings:
    build:
      context: ratings
    image: ${REPO}/rs-ratings:${TAG}
    networks:
      - robot-shop
    depends_on:
      - mysql
  payment:
    build:
      context: payment
    image: signoz/rs-payment:latest
    environment: 
      - DD_AGENT_HOST=datadog-agent 
      - DD_SERVICE="payment"
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    # Uncomment to change payment gateway
    #environment:
      #PAYMENT_GATEWAY: "https://www.worldpay.com"
  dispatch:
    build:
      context: dispatch
    image: ${REPO}/rs-dispatch:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
  web:
    build:
      context: web
    image: ${REPO}/rs-web:${TAG}
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - robot-shop
    # Uncomment to enable Instana EUM
    # environment:
      # INSTANA_EUM_KEY: <your eum key>
      # INSTANA_EUM_REPORTING_URL: https://eum-us-west-2.instana.io
      # INSTANA_EUM_REPORTING_URL: https://eum-eu-west-1.instana.io
  
  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=386b48b3d1fd7bc4fe4408c0c35f5928
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
      - robot-shop
networks:
  robot-shop:

